# 👋 Hi, I'm Michael

💻 Aspiring Web Developer based in Texas, USA  
🌱 Learning HTML, CSS, JavaScript  
🚀 Building real-world projects step by step  
📚 Self-taught & improving daily  

---

## 🛠️ Tech Stack
•⁠  ⁠HTML
•⁠  ⁠CSS
•⁠  ⁠JavaScript (learning)

---

## 📂 Projects
•⁠  ⁠🍽️ Restaurant Website (Live)
•⁠  ⁠🐱 Cat Photo App (FreeCodeCamp)
•⁠  ⁠✈️ Travel Agency Page

---

## 🌐 Live Projects
•⁠  ⁠Cat Photo App: https://michaeltechguy.github.io/cat-photo-app-project/
•⁠  ⁠Restaurant Site - In progess

---

## 📫 Connect With Me
•⁠  ⁠GitHub: https://github.com/MichaelTechGuy
